start-server: sockets/socket.cpp sockets/listeningsocket.cpp sockets/bindingsocket.cpp sockets/connectingSocket.cpp servers/server.cpp servers/test-server/test-server.cpp servers/test-server/test.cpp
	
	g++ sockets/socket.cpp sockets/listeningsocket.cpp sockets/bindingsocket.cpp sockets/connectingSocket.cpp servers/server.cpp servers/test-server/test-server.cpp -o test servers/test-server/test.cpp


