name: Build
on : [push,pull_request]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: compile project
      run : |
       cd C++/Server 
       make start-server

